#!/bin/bash

exec mvn exec:java -Dexec.mainClass="com.boundary.sdk.event.snmp.MIBCompiler" -Dboundary.tools.command.name="$(basename $0)" -Dboundary.tools.snmp.license="$BOUNDARY_MIB_LICENSE" -Dexec.args="$*"
