#!/bin/bash

# Assumes when this script is sourced that current directory is
# the top level of the distribution
export BOUNDARY_SDK_HOME=$PWD

# For the boundary organizational id and api key if the environmnent variable is 
# already set then use that value otherwise set to empty
export BOUNDARY_ORG_ID=${BOUNDARY_ORG_ID:=""}
export BOUNDARY_API_KEY=${BOUNDARY_API_KEY:=""}

# Version of the Boundary SDK distribution
export BOUNDARY_SDK_VERSION=0.02.00

# SNMP4J-SMI License
export BOUNDARY_MIB_LICENSE=${BOUNDARY_MIB_LICENSE:=""}

# Set default location of the SNMP4J-SMI mib repository
export BOUNDARY_MIB_REPOSITORY="$BOUNDARY_SDK_HOME/var/mibrepository"

# Add he bin directory into the PATH
export PATH=$PATH:"$BOUNDARY_SDK_HOME/bin"

# Add convenience alias to change directory to the Boundary Event SDK
alias bsdk='cd $BOUNDARY_SDK_HOME'

# Add convenience alias to view environment
alias benv='env | grep BOUNDARY'
