#!/bin/bash

FACILITY="user"
SEVERITY="err"
MESSAGE="Test_Syslog_Message"

Usage() {
  echo "$(basename $0) [-h] [-f <facility>] [-s <severity>] [-m <message>]"
  echo ""
  echo "facility is one of: auth, authpriv, cron, daemon, ftp, local0-local07, lpr, kern, mail, news, syslog, user, uccp"
  echo "severity is one of: emerg, alert, crit, warning, notice, info, debug"
  exit 0
}

# Check to see if logger is installed and on our path
CheckForLogger() {
   typeset -i rc=0
   typeset -r logger=$(which logger) 
   if [ ! -e "$logger" ]
   then
     rc=1
   fi
   return $rc
}

HandleArguments()
{
   while getopts f:hm:s: option
   do
        case "${option}"
        in
          f) FACILITY=${OPTARG};;
          h) Usage;;
          m) MESSAGE=${OPTARG};;
          s) SEVERITY=${OPTARG};;
        esac
   done
}

SendSyslogMessage()
{
   typeset -r facility=$1
   typeset -r severity=$2
   typeset -r message=$3
   logger -p "$facility.$severity" "$message"
}

Main()
{

  HandleArguments $*

  CheckForLogger
  if [ $? -ne 0 ]
  then
    echo "logger command not available on system please install"
    exit 1
  fi
  SendSyslogMessage "$FACILITY" "$SEVERITY" "$MESSAGE"
}

Main $*
