#!/bin/bash
DATA_FILE_DEV=$BOUNDARY_SDK_HOME/src/test/resources/META-INF/json/notification.json
DATA_FILE_PROD=$BOUNDARY_SDK_HOME/etc/notification.json
if [ ! -r "$DATA_FILE_DEV" ]
then
  if [ ! -r "$DATA_FILE_PROD" ]
  then
    echo "Cannot find notification JSON at $DATA_FILE_DEV or $DATA_FILE_PROD"
  else
    DATA_FILE=$DATA_FILE_PROD
  fi
else
  DATA_FILE=$DATA_FILE_DEV
fi

DATA=$(cat $DATA_FILE)
OUTPUT=$(curl -s -X POST -H "content-type: application/json" -d "$DATA" 'http://0.0.0.0:8127/notification' $PRETTY_CMD)

# If jq is installed then beautify the output
type jq > /dev/null
if [[ $? == 0 ]]
then
  echo $OUTPUT | jq '.'
fi
