#!/bin/bash

#
# Invoked the Service Check sprint file to load routs
#
mvn -q exec:java -Dexec.mainClass="com.boundary.sdk.event.EventApplication" -Dexec.args="$1" -Dboundary.application.context.uri="classpath:META-INF/spring/service-check.xml"
